### ISSUE TITLE
Проверка лабораторной работы 2

### ISSUE THREAD

**Issue by DX37** [DX37/QuadraticEquation#1]
Работу выполнил:
* Курносенко Максим Сергеевич

To: @evgeny-p

**Comment by evgeny-p** [comment]
В целом написано аккуратно. Есть мелкие замечания:

1. Неконсистентное форматирование выражений: обычно бинарные операторы выделяются пробелами.

1. Неконсистентное именование переменных: все в нижнем регистре, `D` — в верхнем.

1. Есть ли причина, по которой Вы используете умножение на `-1` вместо унарного минуса?

1. Коэффициенты `a`, `b`, `c` могут быть числами с плавающей точкой.

**Comment by DX37** [comment]
Исправил в последнем коммите.
-1 я использовал, потому что забыл про существование унарного минуса.

**Comment by evgeny-p** [comment]
Принято. Задачу можно закрывать.
